import type { KnowledgeEntry } from "./types";

export const knowledgeMockData: KnowledgeEntry[] = [
  {
    id: "1",
    title: "Product Return Policy",
    type: "text",
    chunks: ["Step 1: Log in", "Step 2: Click on Dashboard", "Step 3: Navigate menus"],
    updatedAt: "2025-12-14",
    status: "active",
  },
  {
    id: "2",
    title: "Shipping Guidelines",
    type: "file",
    chunks: ["File instructions.pdf"],
    updatedAt: "2025-12-12",
    status: "inactive",
  },
  {
    id: "3",
    title: "Custom FAQ",
    type: "text",
    chunks: ["Q1: How to reset password?", "Q2: How to change email?"],
    updatedAt: "2025-12-10",
    status: "active",
  },
  {
    id: "4",
    title: "Product Return Policy",
    type: "text",
    chunks: ["Step 1: Log in", "Step 2: Click on Dashboard", "Step 3: Navigate menus"],
    updatedAt: "2025-12-14",
    status: "active",
  },
  {
    id: "5",
    title: "Shipping Guidelines",
    type: "file",
    chunks: ["File instructions.pdf"],
    updatedAt: "2025-12-12",
    status: "inactive",
  },
  {
    id: "6",
    title: "Custom FAQ",
    type: "text",
    chunks: ["Q1: How to reset password?", "Q2: How to change email?"],
    updatedAt: "2025-12-10",
    status: "active",
  },
  {
    id: "7",
    title: "Product Return Policy",
    type: "text",
    chunks: ["Step 1: Log in", "Step 2: Click on Dashboard", "Step 3: Navigate menus"],
    updatedAt: "2025-12-14",
    status: "active",
  },
  {
    id: "8",
    title: "Shipping Guidelines",
    type: "file",
    chunks: ["File instructions.pdf"],
    updatedAt: "2025-12-12",
    status: "inactive",
  },
  {
    id: "9",
    title: "Custom FAQ",
    type: "text",
    chunks: ["Q1: How to reset password?", "Q2: How to change email?"],
    updatedAt: "2025-12-10",
    status: "active",
  },
  {
    id: "10",
    title: "Product Return Policy",
    type: "text",
    chunks: ["Step 1: Log in", "Step 2: Click on Dashboard", "Step 3: Navigate menus"],
    updatedAt: "2025-12-14",
    status: "active",
  },
  {
    id: "11",
    title: "Shipping Guidelines",
    type: "file",
    chunks: ["File instructions.pdf"],
    updatedAt: "2025-12-12",
    status: "inactive",
  },
  {
    id: "12",
    title: "Custom FAQ",
    type: "text",
    chunks: ["Q1: How to reset password?", "Q2: How to change email?"],
    updatedAt: "2025-12-10",
    status: "active",
  },
];
